dist: xenial
language: python
python:
  - "3.6"
env:
  - PYTORCH_VERSION=1.3.0
  - PYTORCH_VERSION=1.2.0
  - PYTORCH_VERSION=1.1.0
  - PYTORCH_VERSION=1.0.0
  - PYTORCH_VERSION=0.4.1
install:
  - pip install "torch==$PYTORCH_VERSION"
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - black chatspace --check
  - flake8 chatspace
  - isort -rc -c .
  - python -m pytest
after_success:
  - codecov
